// Shared styles for all components
export const sharedStyles = {
  card: {
    background: "white",
    borderRadius: "12px",
    padding: "2rem",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.1)",
    marginBottom: "1.5rem",
  },
  cardTitle: {
    fontSize: "1.5rem",
    fontWeight: "600",
    color: "#333",
    marginBottom: "1.5rem",
  },
  form: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "1rem",
  },
  label: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.5rem",
    fontSize: "0.9rem",
    fontWeight: "500",
    color: "#555",
  },
  input: {
    padding: "0.75rem",
    borderRadius: "8px",
    border: "1px solid #ddd",
    fontSize: "1rem",
    fontFamily: "inherit",
  },
  select: {
    padding: "0.75rem",
    borderRadius: "8px",
    border: "1px solid #ddd",
    fontSize: "1rem",
    fontFamily: "inherit",
    background: "white",
  },
  textarea: {
    padding: "0.75rem",
    borderRadius: "8px",
    border: "1px solid #ddd",
    fontSize: "1rem",
    fontFamily: "inherit",
    minHeight: "100px",
    resize: "vertical" as const,
  },
  button: {
    padding: "0.75rem 1.5rem",
    borderRadius: "8px",
    border: "none",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    fontSize: "1rem",
    fontWeight: "600",
    cursor: "pointer",
    transition: "transform 0.2s",
  },
  buttonSecondary: {
    padding: "0.75rem 1.5rem",
    borderRadius: "8px",
    border: "1px solid #ddd",
    background: "white",
    color: "#333",
    fontSize: "0.95rem",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  buttonDanger: {
    padding: "0.5rem 1rem",
    borderRadius: "6px",
    border: "none",
    background: "#ef4444",
    color: "white",
    fontSize: "0.9rem",
    fontWeight: "500",
    cursor: "pointer",
  },
  buttonSuccess: {
    padding: "0.5rem 1rem",
    borderRadius: "6px",
    border: "none",
    background: "#10b981",
    color: "white",
    fontSize: "0.9rem",
    fontWeight: "500",
    cursor: "pointer",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    marginTop: "1rem",
  },
  th: {
    textAlign: "left" as const,
    padding: "1rem",
    borderBottom: "2px solid #e5e7eb",
    fontWeight: "600",
    color: "#374151",
    fontSize: "0.9rem",
  },
  td: {
    padding: "1rem",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.9rem",
    color: "#6b7280",
  },
  badge: {
    display: "inline-block",
    padding: "0.25rem 0.75rem",
    borderRadius: "9999px",
    fontSize: "0.8rem",
    fontWeight: "500",
  },
  badgeSuccess: {
    background: "#d1fae5",
    color: "#065f46",
  },
  badgeDanger: {
    background: "#fee2e2",
    color: "#991b1b",
  },
  badgeWarning: {
    background: "#fef3c7",
    color: "#92400e",
  },
  badgeInfo: {
    background: "#dbeafe",
    color: "#1e40af",
  },
  empty: {
    textAlign: "center" as const,
    padding: "3rem",
    color: "#9ca3af",
    fontSize: "1rem",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "1rem",
    marginBottom: "2rem",
  },
  statCard: {
    background: "white",
    borderRadius: "12px",
    padding: "1.5rem",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.1)",
  },
  statValue: {
    fontSize: "2.5rem",
    fontWeight: "bold",
    color: "#667eea",
    margin: "0.5rem 0",
  },
  statLabel: {
    fontSize: "0.9rem",
    color: "#6b7280",
    fontWeight: "500",
  },
  actionButtons: {
    display: "flex",
    gap: "0.5rem",
    justifyContent: "flex-end",
  },
  error: {
    padding: "1rem",
    borderRadius: "8px",
    background: "#fee2e2",
    border: "1px solid #fecaca",
    color: "#991b1b",
    marginBottom: "1rem",
  },
  success: {
    padding: "1rem",
    borderRadius: "8px",
    background: "#d1fae5",
    border: "1px solid #a7f3d0",
    color: "#065f46",
    marginBottom: "1rem",
  },
};
